// <auto-generated>
// This code was generated by a kontent-generators-net tool
// (see https://github.com/kontent-ai/model-generator-net).
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// For further modifications of the class, create a separate file with the partial class.
// </auto-generated>

using System;
using System.Collections.Generic;
using Kontent.Ai.Delivery.Abstractions;

namespace KontentAiModels
{
    public partial class Category
    {
        public const string Codename = "category";
        public const string CategoryIdCodename = "category_id";
        public const string NameCodename = "name";

        public string CategoryId { get; set; }
        public string Name { get; set; }
        public IContentItemSystemAttributes System { get; set; }
    }
}