// <auto-generated>
// This code was generated by a kontent-generators-net tool
// (see https://github.com/kontent-ai/model-generator-net).
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// For further modifications of the class, create a separate file with the partial class.
// </auto-generated>

using System;
using System.Collections.Generic;
using Kontent.Ai.Delivery.Abstractions;

namespace KontentAiModels
{
    public partial class KnowledgeBaseArticle
    {
        public const string Codename = "knowledge_base_article";
        public const string AnswerCodename = "answer";
        public const string AuthorCodename = "author";
        public const string CategoryCodename = "category";
        public const string PermissionCodename = "permission";
        public const string StatusCodename = "status";
        public const string TitleCodename = "title";

        public string Answer { get; set; }
        public IEnumerable<Author> Author { get; set; }
        public IEnumerable<Category> Category { get; set; }
        public IEnumerable<ITaxonomyTerm> Permission { get; set; }
        public IEnumerable<ITaxonomyTerm> Status { get; set; }
        public IContentItemSystemAttributes System { get; set; }
        public string Title { get; set; }
    }
}